name: build & C++ gtest 

on: 
  push:
    branches:
      extio1_test_build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: mkdir build
    - run: cmake -Bbuild
    - run: cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build
    
  test:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build
      - run: ls -la
      - run: ls -la build
      - run: ./build/vector_test
