name: build

on:
  pull_request:
    branches:
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: mkdir build
    - run: cmake -Bbuild
    - run: cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build
