name: build

on:
  pull_request:
    branches:
      - 'release'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: mkdir build
    - run: cmake -Bbuild
    - run: cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build
  test:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build
      - run: chmod +x ./build/text_editor_test
      - run: ./build/text_editor_test

  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "include/**/.h, include/**/.hpp, src/**/*.h, src/**/*.cpp, src/**/*.c"
