name: build

on:
  pull_request:
    branches:
      - 'release'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: mkdir build
    - run: cmake -Bbuild
    - run: cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build
  test:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build
      - run: chmod +x ./build/text_editor_test
      - run: ./build/text_editor_test

  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format
      uses: HorstBaerbel/action-clang-format@1.5
      with:
        scandir: '.'
        excludedirs: 'build, test'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        style: 'google'
